/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 car.gltf 
Author: kevin (ケビン) (https://sketchfab.com/sohyalebret)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2018-lamborghini-aventador-ks-edition-69ed4dbc7b5b416a88280b49d5fe9869
Title: 2018 | Lamborghini Aventador K.S Edition
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/car.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={
              nodes["turismodffturismo_colColMesh_Metal_-_Car_0"].geometry
            }
            material={materials["Metal_-_Car"]}
          />
          <mesh
            geometry={
              nodes["turismodffturismo_colColMesh_Glass_-_Glass_0"].geometry
            }
            material={materials["Glass_-_Glass"]}
          />
        </group>
        <group
          position={[0, 66.932, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <group position={[0.998, 1.303, -0.187]}>
            <mesh
              geometry={nodes.wheels_wheels2_0.geometry}
              material={materials["wheels.2"]}
              position={[0.042, 0, -0.104]}
              rotation={[0, -0.079, 0]}
            />
            <mesh
              geometry={nodes.wheels001_wheels2_0.geometry}
              material={materials["wheels.2"]}
              position={[0.114, -2.987, -0.098]}
              rotation={[0, -0.079, 0]}
            />
            <mesh
              geometry={nodes.wheels002_wheels2_0.geometry}
              material={materials["wheels.2"]}
              position={[-2.122, -2.987, -0.097]}
              rotation={[0, 0.079, 3.136]}
            />
            <mesh
              geometry={nodes.wheels003_wheels2_0.geometry}
              material={materials["wheels.2"]}
              position={[-2.038, 0, -0.104]}
              rotation={[0, 0.079, 3.136]}
            />
            <mesh
              geometry={nodes.wheels004_chassis1_0.geometry}
              material={materials["chassis.1"]}
              position={[0.114, -2.987, -0.098]}
              rotation={[0, -0.079, 0]}
            />
            <mesh
              geometry={nodes.wheels005_wheels1_0.geometry}
              material={materials["wheels.1"]}
              position={[0.114, -2.987, -0.098]}
              rotation={[0, -0.079, 0]}
            />
            <mesh
              geometry={nodes.wheels006_wheels3_0.geometry}
              material={materials["wheels.3"]}
              position={[0.114, -2.987, -0.098]}
              rotation={[0, -0.079, 0]}
            />
            <mesh
              geometry={nodes.wheels007_chassis1_0.geometry}
              material={materials["chassis.1"]}
              position={[0.042, 0, -0.104]}
              rotation={[0, -0.079, 0]}
            />
            <mesh
              geometry={nodes.wheels008_wheels1_0.geometry}
              material={materials["wheels.1"]}
              position={[0.042, 0, -0.104]}
              rotation={[0, -0.079, 0]}
            />
            <mesh
              geometry={nodes.wheels009_wheels3_0.geometry}
              material={materials["wheels.3"]}
              position={[0.042, 0, -0.104]}
              rotation={[0, -0.079, 0]}
            />
            <mesh
              geometry={nodes.wheels010_chassis1_0.geometry}
              material={materials["chassis.1"]}
              position={[-2.122, -2.987, -0.097]}
              rotation={[0, 0.079, 3.136]}
            />
            <mesh
              geometry={nodes.wheels011_wheels1_0.geometry}
              material={materials["wheels.1"]}
              position={[-2.122, -2.987, -0.097]}
              rotation={[0, 0.079, 3.136]}
            />
            <mesh
              geometry={nodes.wheels012_wheels3_0.geometry}
              material={materials["wheels.3"]}
              position={[-2.122, -2.987, -0.097]}
              rotation={[0, 0.079, 3.136]}
            />
            <mesh
              geometry={nodes.wheels013_chassis1_0.geometry}
              material={materials["chassis.1"]}
              position={[-2.038, 0, -0.104]}
              rotation={[0, 0.079, 3.136]}
            />
            <mesh
              geometry={nodes.wheels014_wheels1_0.geometry}
              material={materials["wheels.1"]}
              position={[-2.038, 0, -0.104]}
              rotation={[0, 0.079, 3.136]}
            />
            <mesh
              geometry={nodes.wheels015_wheels3_0.geometry}
              material={materials["wheels.3"]}
              position={[-2.038, 0, -0.104]}
              rotation={[0, 0.079, 3.136]}
            />
          </group>
          <group position={[0, -0.354, 0]}>
            <group position={[0, 0.354, 0]}>
              <mesh
                geometry={nodes.lights001_left_rear_light_0.geometry}
                material={materials.left_rear_light}
              />
              <mesh
                geometry={nodes.glass_inn_glass_0.geometry}
                material={materials.glass}
              />
              <mesh
                geometry={nodes.glass001_glass_0.geometry}
                material={materials.glass}
              />
              <mesh
                geometry={nodes.remap_body4_0.geometry}
                material={materials["body.4"]}
              />
            </group>
            <mesh
              geometry={nodes.chassis_chassis1_0.geometry}
              material={materials["chassis.1"]}
            />
            <mesh
              geometry={nodes.exa_exa1_0.geometry}
              material={materials["exa.1"]}
            />
            <mesh
              geometry={nodes.engine_engine2_0.geometry}
              material={materials["engine.2"]}
            />
            <mesh
              geometry={nodes.interior_interior1_0.geometry}
              material={materials["interior.1"]}
            />
            <mesh
              geometry={nodes.body_body1_0.geometry}
              material={materials["body.1"]}
            />
            <mesh
              geometry={nodes.fender_body4_0.geometry}
              material={materials["body.4"]}
            />
            <mesh
              geometry={nodes.lights_lights0_0.geometry}
              material={materials["lights.0"]}
            />
            <mesh
              geometry={nodes.glass_glass_0.geometry}
              material={materials.glass}
            />
            <mesh
              geometry={nodes.sideskirt_body2_0.geometry}
              material={materials["body.2"]}
            />
            <mesh
              geometry={nodes.fender001_chassis1_0.geometry}
              material={materials["chassis.1"]}
            />
            <mesh
              geometry={nodes.sideskirt001_chassis1_0.geometry}
              material={materials["chassis.1"]}
            />
            <mesh
              geometry={nodes.sideskirt002_engine1_0.geometry}
              material={materials["engine.1"]}
            />
            <mesh
              geometry={nodes.sideskirt003_body4_0.geometry}
              material={materials["body.4"]}
            />
            <mesh
              geometry={nodes.spoiler_spoiler3_0.geometry}
              material={materials["spoiler.3"]}
            />
            <mesh
              geometry={nodes.exa001_chassis0_0.geometry}
              material={materials["chassis.0"]}
            />
            <mesh
              geometry={nodes.engine002_engine0_0.geometry}
              material={materials["engine.0"]}
            />
            <mesh
              geometry={nodes.engine003_engine1_0.geometry}
              material={materials["engine.1"]}
            />
            <mesh
              geometry={nodes.engine004_engine3_0.geometry}
              material={materials["engine.3"]}
            />
            <mesh
              geometry={nodes.interior001_engine3_0.geometry}
              material={materials["engine.3"]}
            />
            <mesh
              geometry={nodes.body001_interior1_0.geometry}
              material={materials["interior.1"]}
            />
            <mesh
              geometry={nodes.body002_body4_0.geometry}
              material={materials["body.4"]}
            />
            <mesh
              geometry={nodes.body003_body3_0.geometry}
              material={materials["body.3"]}
            />
            <mesh
              geometry={nodes.body004_body2_0.geometry}
              material={materials["body.2"]}
            />
            <mesh
              geometry={nodes.spoiler002_body4_0.geometry}
              material={materials["body.4"]}
            />
            <mesh
              geometry={nodes.spoiler003_lights0_0.geometry}
              material={materials["lights.0"]}
            />
            <mesh
              geometry={nodes.spoiler004_glass_0.geometry}
              material={materials.glass}
            />
            <mesh
              geometry={nodes.lights002_body3_0.geometry}
              material={materials["body.3"]}
              position={[0, 0.354, 0]}
            />
            <mesh
              geometry={nodes.lights003_lights0_0.geometry}
              material={materials["lights.0"]}
              position={[0, 0.354, 0]}
            />
            <mesh
              geometry={nodes.lights004_right_front_light_0.geometry}
              material={materials.right_front_light}
              position={[0, 0.354, 0]}
            />
            <mesh
              geometry={nodes.lights005_left_front_light_0.geometry}
              material={materials.left_front_light}
              position={[0, 0.354, 0]}
            />
            <mesh
              geometry={nodes.lights006_right_rear_light_0.geometry}
              material={materials.right_rear_light}
              position={[0, 0.354, 0]}
            />
          </group>
          <group position={[0, 1.229, 0.198]}>
            <mesh
              geometry={nodes.bonnet_ok_body3_0.geometry}
              material={materials["body.3"]}
            />
            <mesh
              geometry={nodes.bonnet_ok001_body4_0.geometry}
              material={materials["body.4"]}
            />
          </group>
          <group position={[0, 0.917, 0.362]}>
            <mesh
              geometry={nodes.windscreen_ok_glass001_0.geometry}
              material={materials["glass.001"]}
            />
            <mesh
              geometry={nodes.windscreen_ok001_chassis1_0.geometry}
              material={materials["chassis.1"]}
            />
            <mesh
              geometry={nodes.windscreen_ok003_windscreen_ok2_0.geometry}
              material={materials["windscreen_ok.2"]}
            />
            <mesh
              geometry={nodes.windscreen_ok004_windscreen_ok3_0.geometry}
              material={materials["windscreen_ok.3"]}
            />
          </group>
          <group
            position={[-1.066, 0.881, -0.003]}
            rotation={[0, Math.PI / 2, 0]}
          >
            <mesh
              geometry={nodes.door_lf_ok_windscreen_ok3_0.geometry}
              material={materials["windscreen_ok.3"]}
            />
            <mesh
              geometry={nodes.glass002_glass001_0.geometry}
              material={materials["glass.001"]}
            />
            <mesh
              geometry={nodes.door_lf_ok001_engine3_0.geometry}
              material={materials["engine.3"]}
            />
            <mesh
              geometry={nodes.door_lf_ok002_interior1_0.geometry}
              material={materials["interior.1"]}
            />
            <mesh
              geometry={nodes.door_lf_ok003_body4_0.geometry}
              material={materials["body.4"]}
            />
            <mesh
              geometry={nodes.door_lf_ok004_body3_0.geometry}
              material={materials["body.3"]}
            />
            <mesh
              geometry={nodes.door_lf_ok005_windscreen_ok2_0.geometry}
              material={materials["windscreen_ok.2"]}
            />
          </group>
          <group
            position={[1.066, 0.881, -0.003]}
            rotation={[0, -Math.PI / 2, 0]}
          >
            <mesh
              geometry={nodes.door_rf_ok_windscreen_ok3_0.geometry}
              material={materials["windscreen_ok.3"]}
            />
            <mesh
              geometry={nodes.glass003_glass001_0.geometry}
              material={materials["glass.001"]}
            />
            <mesh
              geometry={nodes.door_rf_ok001_engine3_0.geometry}
              material={materials["engine.3"]}
            />
            <mesh
              geometry={nodes.door_rf_ok002_interior1_0.geometry}
              material={materials["interior.1"]}
            />
            <mesh
              geometry={nodes.door_rf_ok003_body4_0.geometry}
              material={materials["body.4"]}
            />
            <mesh
              geometry={nodes.door_rf_ok004_body3_0.geometry}
              material={materials["body.3"]}
            />
            <mesh
              geometry={nodes.door_rf_ok005_windscreen_ok2_0.geometry}
              material={materials["windscreen_ok.2"]}
            />
          </group>
          <group position={[-1.196, 1.572, -0.015]}>
            <mesh
              geometry={nodes.bump_front_ok_bump_front_ok4_0.geometry}
              material={materials["bump_front_ok.4"]}
            />
            <mesh
              geometry={nodes.splitter_windscreen_ok3_0.geometry}
              material={materials["windscreen_ok.3"]}
            />
            <mesh
              geometry={nodes.splitter001_engine1_0.geometry}
              material={materials["engine.1"]}
            />
            <mesh
              geometry={nodes.splitter002_body4_0.geometry}
              material={materials["body.4"]}
            />
            <mesh
              geometry={nodes.bump_front_ok001_chassis2_0.geometry}
              material={materials["chassis.2"]}
            />
            <mesh
              geometry={nodes.bump_front_ok002_chassis1_0.geometry}
              material={materials["chassis.1"]}
            />
            <mesh
              geometry={nodes.bump_front_ok003_engine1_0.geometry}
              material={materials["engine.1"]}
            />
            <mesh
              geometry={nodes.bump_front_ok004_body4_0.geometry}
              material={materials["body.4"]}
            />
          </group>
          <group position={[-1.075, -2.104, -0.204]}>
            <mesh
              geometry={nodes.bump_rear_ok_windscreen_ok2_0.geometry}
              material={materials["windscreen_ok.2"]}
            />
            <mesh
              geometry={nodes.plate_plate0_0.geometry}
              material={materials["plate.0"]}
            />
            <mesh
              geometry={nodes.glass004_glass_0.geometry}
              material={materials.glass}
            />
            <mesh
              geometry={nodes.bump_rear_ok001_chassis2_0.geometry}
              material={materials["chassis.2"]}
            />
            <mesh
              geometry={nodes.bump_rear_ok002_engine1_0.geometry}
              material={materials["engine.1"]}
            />
            <mesh
              geometry={nodes.bump_rear_ok003_body4_0.geometry}
              material={materials["body.4"]}
            />
            <mesh
              geometry={nodes.bump_rear_ok004_body3_0.geometry}
              material={materials["body.3"]}
            />
            <mesh
              geometry={nodes.bump_rear_ok005_right_front_light_0.geometry}
              material={materials.right_front_light}
            />
          </group>
          <group position={[0, -0.796, 0.546]}>
            <mesh
              geometry={nodes.boot_ok_body4_0.geometry}
              material={materials["body.4"]}
            />
            <mesh
              geometry={nodes.spoiler001_glass001_0.geometry}
              material={materials["glass.001"]}
            />
            <mesh
              geometry={nodes.spoiler005_lights0_0.geometry}
              material={materials["lights.0"]}
            />
            <mesh
              geometry={nodes.spoiler006_glass_0.geometry}
              material={materials.glass}
            />
            <mesh
              geometry={nodes.spoiler007_spoiler3_0.geometry}
              material={materials["spoiler.3"]}
            />
            <mesh
              geometry={nodes.boot_ok001_chassis1_0.geometry}
              material={materials["chassis.1"]}
            />
          </group>
          <mesh
            geometry={nodes.chassis001_chassis0_0.geometry}
            material={materials["chassis.0"]}
            position={[0, -0.354, 0]}
          />
          <mesh
            geometry={nodes.chassis002_chassis2_0.geometry}
            material={materials["chassis.2"]}
            position={[0, -0.354, 0]}
          />
          <mesh
            geometry={nodes.hub_lf_hub_lf0_0.geometry}
            material={materials["hub_lf.0"]}
            position={[-0.993, 1.173, -0.253]}
            rotation={[0, 0.052, 0]}
          />
          <mesh
            geometry={nodes.hub_rf_hub_lf0_0.geometry}
            material={materials["hub_lf.0"]}
            position={[1.01, 1.173, -0.242]}
            rotation={[0, -0.079, 0]}
          />
          <mesh
            geometry={nodes.hub_rr_hub_lf0_0.geometry}
            material={materials["hub_lf.0"]}
            position={[1.061, -1.676, -0.192]}
            rotation={[0, -0.079, 0]}
          />
          <mesh
            geometry={nodes.hub_lr_hub_lf0_0.geometry}
            material={materials["hub_lf.0"]}
            position={[-1.064, -1.676, -0.208]}
            rotation={[0, 0.109, 0]}
          />
        </group>
        <mesh
          geometry={nodes.turismodffturismo_colShadowMesh_Misc_0.geometry}
          material={materials.Misc}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/car.glb");
